name: .NET

on:
  push:
    branches:
      - main
      - release/**
    tags:
    - v**
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Test
      run: |
        dotnet test tests/* -c Release
    - name: Build packages
      # shell: pwsh
      # Pack as private build for now
      run: |
        dotnet pack -c Release -o ./packages /p:PublicRelease=false
    
    - name: Integration test
      run: |
        dotnet restore ./integration-test/Chibi.Ui.SourceGenerators.NugetTests/ -s ./packages
        dotnet test .\integration-test\Chibi.Ui.SourceGenerators.NugetTests\ --no-restore
    
    - name: Publish packages
      uses: actions/upload-artifact@v2
      with:
        name: Packages
        path: |
          ./packages
        
